### ISSUE TITLE
Filters get deleted from classes

### ISSUE THREAD

**Issue by prescod** [carltongibson/django-filter#1056]
I found this behaviour surprising. I needed the list of filters on my class for a reason and they had been deleted.

https://gist.github.com/prescod/148e0f6cbb70f29be317b4507796c763

I would guess that this behaviour is caused by the .pop in     

```python
def get_declared_filters(cls, bases, attrs):
        filters = [
            (filter_name, attrs.pop(filter_name))
            for filter_name, obj in list(attrs.items())
            if isinstance(obj, Filter)
        ]
```

**Comment by rpkilby** [comment]
Hi @prescod. This is a behavior that's common in Django models, forms, etc... for example:

```python
>>> from django import forms
>>> class Foo(forms.Form):
...     bar = forms.CharField()
... 
>>> Foo.bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Foo' has no attribute 'bar'
```

The short version is that there is some metaclass magic that removes the declared fields from the class, storing them in an `OrderedDict`. If you need to access the actual filter instances, there are a few options:

```python
Foo.declared_filters['bar']
```
All *declared filters* are stored as a dict under this class attribute.

```python
Foo.get_filters()['bar']
```
The `get_filters()` classmethod returns a dict that contains the declared filters, as well as those generated from the `Meta.fields` option.

```python
Foo().filters['bar']
```
Instances will have a `.filters` attribute set, containing per-instance copies of the above filters.

Hope that helps.

**Comment by prescod** [comment]
Thank you. That is very helpful. I'm not sure why it is important that the filters be removed from the classes, but at least now I know where to find them. Thanks again.

**Comment by rpkilby** [comment]
Good question. I know that there are several reasons why collecting the filters into a dict is beneficial: 
- The `.filters` dict contains *all* filters, including those that are declared, generated from the `Meta.fields` option, and those inherited from base classes. 
- Since all of the filters are collected into a single dict, it's easier to iterate over them. Otherwise, you'd have to iterate over the class vars and do an `isinstance` check on each attribute.
- It's also easier to dynamically modify the collection of filters. e.g., you could add/remove filters from the dict, or modify filters in the `FilterSet.__init__` method.

That said, I'm not entirely sure why the filters need to be *removed* from the class itself. I don't know what benefit that brings.

----

Also, slight correction. 
```python
# this
Foo.get_filters()['bar'] 

# should be
Foo.base_filters['bar']
```

`.base_filters` is just the stored result of `.get_filters()`.

https://github.com/carltongibson/django-filter/blob/9d921c726895d111b99604c914e50c36fe14091e/django_filters/filterset.py#L71

**Comment by rpkilby** [comment]
Either way, if you're modifying your filters, it should probably be done per filterset instance, possibly in `FilterSet.__init__`.
