### ISSUE TITLE
DjangoFilterBackend not filtering when '__in' filter is an empty list

### ISSUE THREAD

**Issue by Kurara** [carltongibson/django-filter#1126]
I created a custom backend with a custom query parameter that in base at other model data and calling _compose_list() return a list of current model data that is filled into an ___in_ property:

```
class CustomFilterBackend(filters.DjangoFilterBackend):
    """
    """
    def get_filterset_kwargs(self, request, queryset, view):
        kwargs = super().get_filterset_kwargs(request, queryset, view)

        if 'custom_filter' in kwargs.get('data'):
            new_dict = kwargs.get('data').copy()
            other_model_data_list = new_dict.pop('custom_filter')
            profiles_list = self._compose_list(other_model_data_list)
            if len(profiles_list) > 0:
                    new_dict['profile__id__in'] = ','.join(
                        str(id) for id in profiles_list
                    )
           else:
                    # This filter does nothing!!!
                    new_dict['profile__id__in'] = ''

            kwargs['data'] = new_dict

        return kwargs
```

This is working when **profiles_list** is not empty. If it's not empty the queryset it does to database is:

> SELECT `keyword`.`id`, `keyword`.`profile_id`, `keyword`.`keyword` FROM `keyword` WHERE `keyword`.`profile_id` IN (56, 68)

But when **profiles_list** is not empty the query it does instead is:

> SELECT `keyword`.`id`, `keyword`.`profile_id`, `keyword`.`keyword` FROM `keyword`

It should add `keyword`.`profile_id` IN () to query, right?

**Comment by carltongibson** [comment]
Should `'profile__id__in'` not be `'profile_id__in'`?

**Comment by rpkilby** [comment]
It may seem unintuitive, but empty values are skipped when filtering. This is necessary, since HTML forms submit all inputs, regardless of whether those inputs have a non-empty value.
https://github.com/carltongibson/django-filter/blob/a5b4d0299ec04dcb103dc37291001fb268107c66/django_filters/filters.py#L143-L145
https://github.com/carltongibson/django-filter/blob/a5b4d0299ec04dcb103dc37291001fb268107c66/django_filters/constants.py#L5

Although I wouldn't recommend it, if you want to override this behavior, you'll need something like:

```python
class NumberInFilter(BaseInFilter, NumberFilter):
    def filter(self, qs, value):
        if self.distinct:
            qs = qs.distinct()
        lookup = '%s__%s' % (self.field_name, self.lookup_expr)
        qs = self.get_method(qs)(**{lookup: value})
        return qs


class MyFilterSet(FilterSet):
    profile__id__in = NumberInFilter(field_name='profile__id', lookup_expr='in')
```

Also, the logic in your filter backend seems fairly specific, and should probably be moved to the your filterset's `__init__`.

**Comment by Kurara** [comment]
Grazie @rpkilby Tutto chiaro adesso :)
