### ISSUE TITLE
FILTERS_DEFAULT_LOOKUP_EXPR breaks Filters

### ISSUE THREAD

**Issue by profhase** [carltongibson/django-filter#1282]
I am using
```
django-filer == 2.4.0
```
Having the following filter:

```
class MyObjectFilter(django_filters.FilterSet):

    class Meta:
        model = MyObject
        fields = {
            'object_type': ['exact',],
            'object_id': ['exact']
        }

```
The Filtering (DRF) works perfectly fine.

As soon as I set 

```
FILTERS_DEFAULT_LOOKUP_EXPR = 'icontains'
```

My view returns *all* objects on filtering (so the result is not filtered anymore

**Comment by panosangelopoulos** [comment]
Hi @profhase as soon as you set the `FILTERS_DEFAULT_LOOKUP_EXPR` your filters will work with the `icontains` lookup instead of your `exact` or any other lookup which you set to your filter class.

Thus, it will return all the objects based on the icontains lookup. Could you please be sure that an object which doesn't fit with the `icontains` lookup is returned?

**Comment by profhase** [comment]
@panosangelopoulos You are right, I am not sure if this is the desired behaviour, though:

I would think that my filter configuration would take precedence over the `FILTERS_DEFAULT_LOOKUP_EXPR` (The variable suggests this is default - not a global override). What do you think?
