### ISSUE TITLE
Is it possible to switch the documentation theme?

### ISSUE THREAD

**Issue by baseplate-admin** [carltongibson/django-filter#1610]
Hi,

Thanks for creating this awesome package. I am a big fan of this project ( been using it in production for half a year )

Now,
I was wondering if it was possible to switch to a better documentation theme?

Since we are using Sphinx, Maybe [`furo`](https://github.com/pradyunsg/furo) is a good candidate?

Thanks a bunch :D

---

Some of projects that uses `furo`:

* [`django-mysql`](https://django-mysql.readthedocs.io/en/latest/)
* [`urllib3`](https://urllib3.readthedocs.io/en/stable/)
* [`black`](https://black.readthedocs.io/en/stable/)
* [`pip`](https://pip.pypa.io/en/stable/)

**Comment by carltongibson** [comment]
Hi yes! 🙌 

Thanks i'd be really happy to accept this. 

Something changed in RTD recently and the old theme, which was OK, stopped working, so getting Furo going would be perfect!

Thanks for the input! 🎁

**Comment by jnns** [comment]
Hello Carlton, hello @baseplate-admin,

I took a stab at changing the docs template to Furo. It seems to have built just fine on https://django-filter-furo.readthedocs.io/. Feel free to check it out.

As it can be confusing to also have outdated documentation available under
https://dwbf.readthedocs.io/ and https://rpkilby.github.io/django-filter/, it's very nice if the canonical documentation stands out with a modern theme. 

I will remove the Furo documentation variant from ReadTheDocs once this issue is closed.
