### ISSUE TITLE
Should raise when a filter class for a field cannot be found (and strict=True)

### ISSUE THREAD

**Issue by davidfischer-ch** [carltongibson/django-filter#186]
One of my models is using a UUIDField as a "uuid" field.

I setup a FilterSet for this model and I remarked by using it that the filter set is returning all records when filtering by "uuid".

This is an unexpected behavior especially because we can set a argument, strict=True that obviously should means "raise something when you fail". But it doesn't.

I checked the code of this project and it seem that the implementation of filter_for_field returns None in case of failure. This is a good behavior if some code using it will handle such case. Unfortunately it isn't.

So please raise an exception when the FilterSet is unable to find a proper filter Field for a given model Field.

Thanks.

**Comment by paulcollinsiii** [comment]
@carltongibson so I just ran into this on my end in Django 1.8. I'm using UUID's for all my pk fields. When I explicitly added 
```python
class MyFilter(...):
    class Meta:
        field = ['some_relation__id']
```
well it turns out the filter never gets added. This is pretty silent about how it's not adding a filter for a field that while valid, it can't figure out how to filter. Personally I'd like this to be an error during class instantiation so it's obvious to the dev that a requested filter type is going to be dropped.

**Comment by paulcollinsiii** [comment]
as a quick followup, updating that psuedo-code class above with something like
```python
from django.db import models as django_models

class MyFilter(...):
    filter_overrides = {
        django_models.UUIDField: {'filter_class': django_filters.CharFilter}
    }
   class Meta:
        field = ['some_relation__id']
```
Fixes it since that filter is then added to the list

**Comment by carltongibson** [comment]
OK, there's two things going on here. 

1. Failing silently: BAD
2. Not covering all Django provided field types: BAD.

I'll merge #136 to address 1. I'll look at 2 for the new fields as well. 

Thanks for the follow up.
