### ISSUE TITLE
TreeForeignKey widget

### ISSUE THREAD

**Issue by mazing** [carltongibson/django-filter#195]
When I use `django-mptt` I use `TreeForeignKey` which changes the widget.

In `django-filter` it still uses the traditional widget. Shouldn't it use the widget specified for the model field if such is specified?

**Comment by 57even** [comment]
Hi

In django-mptt you specify a foreign key as `parent = TreeForeignKey(to='self')`. The field `TreeForeignKey` inherits from the normal field `ForeignKey` but with a custom widget.

My question was if django-filter shouldn't check the field's widget instead of just assuming that the widget should be the normal widget `Select` instead of the widget specified in the model fields.

I hope you get what I mean. I know I can set the widget but I think a filter like this:

    class MyFilter(django_filters.FilterSet):
        class Meta:
            model = MyModel
            fields = [
                'group',
            ]

should find the correct widget for field `group` automatically.

**Comment by carltongibson** [comment]
OK. I understand. But I'm going to say you need to do this yourself. 

DF defines a default mapping between Django provided model fields and DF provided filter classes. Beyond that it's out of scope. 

Define a Filter class with the widget you need and declare it on your filter — That's one line. If you're doing it a lot you may want to declare a base FilterSet class for your project declaring `filter_overrides` with a `mptt.TreeForeignKey` key.
