### ISSUE TITLE
Add Any & None Handling to ChoiceFilter (and subclasses)

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/django-filter#261]
ChoiceFilter does not provide an empty choice to skip filtering on the field. 

Users can work around by adding the extra choice in `__init__`...

```
def __init__(self, *args, **kwargs):
    super(MyFilterSet, self).__init__(*args, **kwargs)
    self.filters['a_filter_field'].field.choices.insert(0, ('', u'---------'))
```

(Example adapted from #36)

... but it would be nice to have API to do this declaratively. 

As [pointed out in the discussion on #36](https://github.com/alex/django-filter/issues/36#issuecomment-4350491) we can't just automatically insert the extra choices since only certain widgets require it. 

An additional requirement (#214) is to filter for None values — i.e. "Any" means "Don't filter" where here we filter but only for None values. 

An overly simple ChoiceFilter subclass demonstrating **both** of these behaviours filtering against a related `Type` field looks like this: 

```
class TypeFilter(django_filters.ChoiceFilter):
    @property
    def field(self):
        if not hasattr(self, '_field'):

                choices = [
                    ('ANY',  'Anywhere'),('NONE', 'None'),
                ]

                type_qs = self.extra["queryset"]

                # This is coupled to the specific model
                choices += [('Type', [(t.pk, t.title) for t in type_qs],)]

                self._field = forms.ChoiceField(choices=choices, required=self.required, label=self.label, help_text='')

        return self._field

    def filter(self, qs, value):
        if value == '':
            return qs
        if value == 'ANY':
            return qs
        elif value == 'NONE':
            return qs.filter(type_id=None)
        else:
            return qs.filter(type_id=value)
```

Here we add the additional choices when generating the field and look out for them when filtering. We're not dealing with excludes, or distinct, or lookup type, or... 

Goals: 
- [ ] Document this better so users can see that implementing their own behaviour here is simple enough. 
- [ ] Work this into ChoiceFilter with a decent API.

**Comment by marcus1487** [comment]
@carltongibson This is very close to what I was referring to in #252, but I think what I really want is an AllModelsFilter analogous to the AllValuesFilter, but for a ForiegnKey field. I am having trouble figuring out how to extend your example here to adapt to the model filter type since each option is simply a model instance and a None choice of any type (string or None) does not qualify as a queryset. I think this should possibly be a separate issue. My issue is certainly related to this issue, but I think the addition of an AllModelsFilter is enough to warrant a separate issue.

**Comment by carltongibson** [comment]
@marcus1487, I'm not understanding your issue. You want something like `qs.filter(fk=None)` right? (That gets you the QuerySet you're after yes?) What can't you do here? Can you put together a test case showing the behaviour you expect but can't get?

**Comment by marcus1487** [comment]
My issue is that I have to instantiate a Model type filter with a QuerySet. 

For example, let's say I have a Book model with a ForiegnKey field Author which can be null. Then when I set up a filter of books for authors I have to pass a QuerySet composed of Author objects. If I compose this from the `Authors.objects.all()` method then there is obviously no null option since Null/None is not a member of the authors table. If I compose the queryset from the foriegn keys of the books table I cannot get the author model objects. 

Maybe this is my problem. Is there a way to get the author models as a queryset from a query of the available author objects through the Books model. `.objects.values('author')` just gives me a dictionary which does not allow any Model `field_class` to have access to the correct objects. I may be missing something pretty straightforward, but I am getting really confused about what to do here.

**Comment by carltongibson** [comment]
Hi @marcus1487 — from your explanation I'm not sure what issue it is you're facing. It seems like a usage question though. 

If you need help can I ask you to send an email to the [Mailing List](https://groups.google.com/forum/#!forum/django-filter)? Therein please give a **code** example of where you're getting stuck and I'll see if I can say something sensible. Thanks.
