### ISSUE TITLE
Exclude in filterset

### ISSUE THREAD

**Issue by MichaelPavlov** [carltongibson/django-filter#421]
I'm trying to exclude products in my app which does not have a price set. Trying this code

    class CCFilter(FilterSet):
        country = ChoiceFilter(choices=country_values)
        brand = ChoiceFilter(choices=brand_values)
        type = ChoiceFilter(choices=type_values)

        class Meta:
            model = CC
            exclude = {
                "price": None,
            }
            order_by = ['price']
            fields = {
                'country': ['exact'],
                'brand': ['exact'],
                'type': ['exact'],
            }

But it wont exclude items with price == None. Documentation doesn't give an example, how to use this feature. Can you guys give me a hint, what am I doing wrong?

**Comment by MichaelPavlov** [comment]
Looks like this exclude option excludes whole field. And doesn't have to do with filtering queryset.

**Comment by MichaelPavlov** [comment]
Got it work. Overrided get_queryset method of my FilterView with excluded option and added model parameter.

**Comment by rpkilby** [comment]
@MichaelPavlov the `Meta.exclude` option behaves similarly to the same option in django's `ModelForm`s. There is an `exclude` parameter that can be passed to individual filters. ex:

```py
```

**Comment by rpkilby** [comment]
@MichaelPavlov - as you figured out, the `Meta.exclude` option behaves similarly to the same option in django's `ModelForm`s. 

If you're trying to create a filter that allows users to exclude unset prices, you could also do something like the following (assuming that the field is nullable):

```py
class CCFilter(FilterSet):
    price_is_set = BooleanFilter(name='price', lookup_expr='isnull', exclude=True)
    ...
```

A `?price_is_set=true` query would translate to `CC.objects.exclude(price__isnull=True)`. Note that the `exclude` parameter operates differently from `Meta.exclude`. This just tells the filterset to call `.exclude()` instead of `.filter()`

**Comment by jdejoode** [comment]
The `exclude=True` option is part of the documentation, but I found it here first. Maybe the docs could add an example such as, 'If you want to filter on 'not contains' or 'not exact' then you can use the option `exclude=True` to do so. That might lead Google to the right place.
