### ISSUE TITLE
django/template/base.py: DeprecationWarning:__getitem__ QuerySet methods are no longer proxied.

### ISSUE THREAD

**Issue by dilyanpalauzov** [carltongibson/django-filter#532]
class BaseFilterSet deprecates __getitem__ and defines property called  "form".

I have a class, that derives from django_filters.views.FilterView.  When it is rendered with Django 1.10.2, indjango/template/base.py:885 is called current=current[bit] with bit = "form" and current=myFilterVeiw.  This creates
```
/opt/virtualenv/django/lib/python3.4/site-packages/django/template/base.py:885:
DeprecationWarning: QuerySet methods are no longer proxied. See: https://django-filter.readthedocs.io/en/latest/migration.html
  current = current[bit]"
```

**Comment by carltongibson** [comment]
You need to read the docs at the URL provided in the error message: https://django-filter.readthedocs.io/en/latest/migration.html#queryset-methods-are-no-longer-proxied

**Comment by dilyanpalauzov** [comment]
I beleive it is not me who calls myFilterSet['form'] <=> myFilterSet.__getitem__('form'), but Django itself.  So in this case __getitem__ shall be altered to throw an exception, when myFilterSet['form'] is called (like not subscriptable).

**Comment by rpkilby** [comment]
The referenced PR provides context. In short, this is a side effect of the DTL's variable lookup [rules](https://docs.djangoproject.com/en/1.10/ref/templates/language/#variables). The upcoming `1.0` release will remove the deprecated methods and the warnings will cease.

If you can't just ignore the errors for the short term, you have two options:
- add a warnings filter to ignore the deprecation warning. 
- Subclass the view and pass the `filter.form` in the context instead of the `filter` itself.

Yep, this is a problem with the DTL's variable lookup rules.
