### ISSUE TITLE
'Filter' object is not iterable

### ISSUE THREAD

**Issue by dezinfo** [carltongibson/django-filter#589]
It worked good but recently had appeared error **"'Filter' object is not iterable"** when I try to use FilterSet in my ListView

Django 1.10.3

@ I deploy my project to webserver and there isn't any problem with filter. Error appears only on my local workstation. I haven't any ideas what to do. Recently I updated  my  PyCharm and solved issue with psycopg2

http://stackoverflow.com/questions/32978365/how-do-i-run-psycopg2-on-el-capitan-without-hitting-a-libssl-error

**Comment by rpkilby** [comment]
My guess is that your webserver is running django-filter 0.15.x, and your local workstation is running the 1.0 release. The version discrepancies would explain the differing behavior since there were a number of deprecations introduced in 0.15.x that were finalized/removed in the 1.0 release. One of these deprecations is that [`FilterSet`s no longer proxy `QuerySet` methods](https://django-filter.readthedocs.io/en/develop/guide/migration.html#queryset-methods-are-no-longer-proxied), including `__iter__`. Your template may be iterating over the filterset, and it needs to iterate over `.qs` property instead.

**Comment by carltongibson** [comment]
Assuming @rpkilby's response is the correct one here. If not we can re-open.
