### ISSUE TITLE
queryset overwritten in FilterView

### ISSUE THREAD

**Issue by fkdeboer** [carltongibson/django-filter#594]
Hi,
Using the FilterView as follows (for a table), is not working as expected, as the queryset gets overwritten:
     
```
def get_table_data(self):
        qs= Foo.objects.annotate(bar=Count('bar')).values('bar')
        self.filter = self.filterset_class(self.request.GET, queryset=qs)
        return self.filter.qs
```

 I would expect that the queryset provided at instantiation of the filter is used, but it gets overwritten somewhere in the FilterView by a generic queryset of the model given in the filter (Foo.objects.all() ), losing the annotation and values. 
overwriting self.get_queryset() in the view solves this:

 ```
def get_queryset(self):
          return Foo.objects.annotate(bar=Count('bar')).values('bar')
```

but in my opinion if a queryset is given when calling the FilterSetClass, this should be used any time.

**Comment by rpkilby** [comment]
Hi @fkdeboer. Are you're mixing `FilterView` with `SingleTableView` from django-tables2? If so, could you provide a more complete sample of your view class? Depending on class hierarchy, it's possible that `get_table_data()` isn't actually called.

**Comment by fkdeboer** [comment]
I'm using SingleTableMixin from django-tables2 as follows:

```

class SpeciesListView(SingleTableMixin, FilterView):
    model = Species
    template_name = 'species/species_list.html'
    table_class = SpeciesTable
    filterset_class = SpeciesFilter
      
    def get_queryset(self):
      
        species= Species.objects.with_name().values('name', 'scientific_name', 'pk')
        return species

    def get_table_data(self):
        species=self.get_queryset()
        self.filter = self.filterset_class(self.request.GET, queryset=species)
        return self.filter.qs.distinct().order_by('name', )
```

the SpeciesQueryset with_name() annotates 'name' to the queryset.
The above code works for me correctly.
However, I would expect that I can provide the queryset directly in
` self.filter = self.filterset_class(self.request.GET, queryset=species) `
which does not work without the` get_queryset`. I thought this was because of the filterview, as I use the combination `SingleTableMixin, FilterMixin, DetailView` a lot without any problems. But I can be mistaken of course.

**Comment by rpkilby** [comment]
I see what's happening - your view is creating two different filtersets. 

- [`FilterView.get()`](https://github.com/carltongibson/django-filter/blob/1.0.1/django_filters/views.py#L59-L67) constructs the first filterset with keyword args from `get_filterset_kwargs()`. 
- `get_filterset_kwargs()` gets the `queryset` kwarg from `get_queryset()`.
- [`get_queryset()`](https://github.com/django/django/blob/1.10.5/django/views/generic/list.py#L26-L53) essentially returns `model.objects.all()`, which is why you are having to override it.
- `FilterView.get()` then passes `filter=filterset` and `object_list=filterset.qs` as additional context to `get_context_data()`.
- `SingleTableMixin` overrides [`get_context_data()`](https://github.com/bradleyayers/django-tables2/blob/v1.2.9/django_tables2/views.py#L101-L109), which will call your `get_table_data()` method. 
- In `get_table_data()`, you initialize the second filterset, then return a new queryset that is distinct+ordered. 

By default, [`get_table_data()`](https://github.com/bradleyayers/django-tables2/blob/v1.2.9/django_tables2/views.py#L86-L93) returns the `object_list` if it's present on the view. You should be able to use super without having to create an entirely new filterset instance.

```py
class SpeciesListView(SingleTableMixin, FilterView):
    model = Species
    template_name = 'species/species_list.html'
    table_class = SpeciesTable
    filterset_class = SpeciesFilter
      
    def get_queryset(self):
        return self.model.objects.with_name().values('name', 'scientific_name', 'pk')

    def get_table_data(self):
        data = super(SpeciesListView, self).get_table_data(self)
        return data.distinct().order_by('name', )
```

Side note: 
The template is only rendered with the contents returned from `get_context_data()`. If your template renders `{{ filter.form }}` or `{{ filter.qs }}`, then it's actually operating on the *first* filterset constructed in the `get()` handler, since this was passed as extra context.  Setting `self.filter = ...` in `get_table_data()` has no effect, since the view's attributes are not included as context*. 

* Although, you *could* indirectly access it as `{{ view.filter }}` since the view is usually included in the context data.

**Comment by fkdeboer** [comment]
@rpkilby 
Ryan, thanks a lot! It's clear to me now.
