### ISSUE TITLE
How to pass lookup_expr argument to method

### ISSUE THREAD

**Issue by weasteam** [carltongibson/django-filter#614]
This is not a issue, but I really have no idea where to get the help.

I am creating a custom lookup and hoping to interact the lookup_expr with the method I created, but have no clue how to do that. I have checked all documentation at http://django-filter.readthedocs.io/en/latest/ref/filters.html#filter-method, but result in nothing.

Any tips would be greatly appreciated:

Specify a field:

`fields = {'count':['exact','lt','gt','gte','lte']}`

Create the searching field:

`count = django_filters.CharFilter(name='count', method='filter_count')`

Create the searching method:

```
def filter_count(self, queryset, name, value):
    return queryset.filter(id__in=Some searching Query.annotate(count=Count('id')).filter(count__gte=value).values_list('id',flat=True)).distinct()
```

How to replace **__gte** with the lookup_expr that defined in the fields?

**Comment by carltongibson** [comment]
Hi @weasteam — the mailing list **is** appropriate place — but follow-up may not be instant. (I saw your mail.)

Since you're here, I'll just say as way of pointer:

* The `fields` dict is instead of declaring the field by hand (not as well)
* Your declared field and method look fine, but...
* You'll need to use something like a MultiWidget to get both the count value and the lookup type from the query string. 

Try passing `lookup_expr=['exact','lt','gt','gte','lte']` to the CharFilter declaration. That should create the multiwidget for you. 

Print the form, see what data gets submitted, there's a chance it could just work.

If not please follow up on the mailing list.
