### ISSUE TITLE
django 1.11 lookup to an unrecognized field type JSONField

### ISSUE THREAD

**Issue by mapleflow** [carltongibson/django-filter#675]
AssertionError: ProductFilter resolved field 'attrs' with 'exact' lookup to an unrecognized field type JSONField. Try adding an override to 'Meta.filter_overrides'. See: https://django-filter.readthedocs.io/en/develop/ref/filterset.html#customise-filter-generation-with-filter-overrides

Also ArrayField, SearchVectorField like this, how to solve it ?

Env:

	Ubuntu 14.04
    Python 3.4
	Django (1.11)
    django-filter (1.0.2)
    django-filters (0.2.1)
    djangorestframework (3.6.2)

Code: 
	
    # model.py
	class Proudct(models.Model):
    	attrs = JSONField(
            blank = True,
            null = True
        )
        
	# filter.py
    class ProductFilter(django_filters.FilterSet):
    	class Meta:
        	fields = '__all__'
            model = Product

**Comment by carltongibson** [comment]
Currently we have no built in support for JSONField. c.f. #426 and #583.

I'd be inclined to begin passing a `method` that handled your particular filtering logic. Maybe we can provide a generalised solution from there. 

I'm very happy to look at positive suggestions but this isn't something I consider an active issue right now — simply because a generalised solution hasn't yet presented itself. On that basis I'm going to close this — but if you do have suggestions please do follow up.
