### ISSUE TITLE
How to define DateRangeFilter options

### ISSUE THREAD

**Issue by tuxedojoe** [carltongibson/django-filter#699]
I really like this package! 

However, I get stuck trying to change the DateRangeFilters. I can't seem to find any information on how to custom date ranges. For example, I need it to be Today, in 2 weeks from now, in a month from now, in a year from now. Any help appreciated.

**Comment by rpkilby** [comment]
Hi @tuxedojoe - this is more of a usage question than a bug report/feature request. I'd recommend asking  on Stack Overflow as you're more likely to get a timely response. 

----

That said, it's not entirely clear what isn't working. I'd recommend checking the querystring (are you actually submitting the correct query params) and the output of `FilterSet` (is the resulting query sensible). You can check the query with:

```python
print(str(PosterFilter(data=request.GET, queryset=Poster.objects.all()).qs.query))
```

Additionally, it shouldn't be necessary to duplicate that much code in your filter. You should be to just do:

```python
import django_filters


class myDateRangeFilter(django_filters.DateRangeFilter):
    options = {
        '': (_('Any date'), lambda qs, name: qs),
        1: (_('Today'), lambda qs, name: qs.filter(**{
            '%s__year' % name: now().year,
            '%s__month' % name: now().month,
            '%s__day' % name: now().day
        })),
        2: (_('Within 2 weeks'), lambda qs, name: qs.filter(**{
            '%s__gte' % name: _truncate(now()),
            '%s__lt' % name: _truncate(now() + timedelta(days=14)),
        })),
        3: (_('This month'), lambda qs, name: qs.filter(**{
            '%s__year' % name: now().year,
            '%s__month' % name: now().month
        })),
        4: (_('This year'), lambda qs, name: qs.filter(**{
            '%s__year' % name: now().year,
        })),
    }
```

Notice the inheritance from `DateRangeFilter` instead of from `ChoiceFilter`.
