### ISSUE TITLE
Unable to get the desired result due to uppercase or lowercase difference! Help

### ISSUE THREAD

**Issue by ZaibiMughal** [carltongibson/django-filter#704]
I just want to say that your package is awesome. I got what i was seacrhing for. The only issue i am facing right now is that lets suppose my product name is Red. SO when i use filter and type 'red' . It does not show the product unless or untill i re-type 'red' with r as capital like 'Red'. How can i remove this issue. 
I am doing a university project and really need your help asap.

**Comment by ZaibiMughal** [comment]
@rpkilby can you help me out?

**Comment by rpkilby** [comment]
Hi @ZaibiMughal - it's recommended that you ask questions on Stack Overflow, since you're more likely to get a timely response. The issue tracker is intended more for bug reports and feature requests.

----

That said, you can fix this by using an appropriate lookup expression. By default, filters use an exact match, however you can use any valid lookup. In this case, appropriate lookups might be `iexact` or `icontains`.

```python
class ProductFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(name='name', lookup_expr='iexact')
```
