### ISSUE TITLE
Please reopen issue #137

### ISSUE THREAD

**Issue by atkawa7** [carltongibson/django-filter#711]
The problem still persist

**Comment by carltongibson** [comment]
Ref #137. 

@atkawa7 There was a lot going on it that thread. The CSV based filtering was implemented. No-body was able/willing to spend the time to narrow down the issue to a specific reproducible example. In the end it wasn't even clear exactly who had which issue and which requirement. I'm certainly not going to re-open it. 

This issue as created is particularly unhelpful: there's nothing actionable here, and no attempt to describe the actual issue you're facing. 

I'll leave this open for a day or so to give you the chance to edit the issue title and description to explain what you're trying to do and the issue you're facing. Otherwise there's no help to be given.

**Comment by atkawa7** [comment]
@carltongibson I was having the same issue as @apelliciari  But managed to fix the issue I was having by using  the  method suggested by @ddevlin.

**Comment by rpkilby** [comment]
@atkawa7 - I would not recommend that solution, since it doesn't perform input validation. If you're looking to create a custom CSV filter, I'd look at [this](https://django-filter.readthedocs.io/en/develop/guide/tips.html#filter-and-lookup-expression-mismatch-in-range-isnull) example in the docs.

The relevant bits:

```python
class NumberInFilter(django_filters.BaseInFilter, django_filters.NumberFilter):
    pass

class ProductFilter(django_filters.FilterSet):
    categories = NumberInFilter(name='category', lookup_expr='in')
    uncategorized = django_filters.BooleanFilter(name='category', lookup_expr='isnull')
```

**Comment by atkawa7** [comment]
@carltongibson @rpkilby Thank you for you suggestion. What if you are trying to query the following 
`/path?d=A,B,C` where d can be A, B, C, D, E when d is not a number. In that case what is appropriate solution

**Comment by rpkilby** [comment]
Hi @atkawa7 - I would use the most appropriate filter for your use case. eg, if `d` expects text, then mix in a `CharFilter` instead of a `NumberFilter`. If you want ISO 8601 datetimes, mix in the `ISODateTimeFilter`. The `BaseInFilter` and `BaseRangeFilter` were designed to be mixed in such that the second filter class performs validation for the individual input values.
