### ISSUE TITLE
Proposal for creating ListField

### ISSUE THREAD

**Issue by kalombos** [carltongibson/django-filter#724]
Hello,

I use django_filter for django rest framework mostly and i need something like MultipleChoiceFilter but without choices. I need it pretty often.

I found some solution with BaseCSVFilter [here](http://stackoverflow.com/questions/41194200/django-filter-with-drf-how-to-do-and-when-applying-multiple-values-with-the/44066468) but it is not working for me because i have commas in values.

So i writed custom ListField for that, here  [ the code](http://stackoverflow.com/questions/41194200/django-filter-with-drf-how-to-do-and-when-applying-multiple-values-with-the/44066468#44066468)

I thought it would be great if something like the ListFIeld would be in django_filters package. Do you have plans to realize it? Or i could try to realize it by myself and make a PR. Please tell me what you think about the idea.

**Comment by carltongibson** [comment]
> ...because i have commas in values.

Well, you can either escape the commas, or build a widget with a different divider...

The alternative then is to create a custom widget what implements `value_from_datadict` to call `getList` on the `QueryDict`, rather than `get`. (Then you can have `?key=value1&key=value2` in your URL.)

Both of these solutions need to live in user land code. Al least to begin: I'm always interested to see the final solutions. Maybe we can adapt what we have. 

With a custom widget you should be able to use `BaseCSVField`. (It's already set up to take a list.) (We could perhaps document that better.) If not you could show us what works (and what doesn't) and we can have a look. 

At this point I don't think adding an additional Field type is necessary.

**Comment by carltongibson** [comment]
Possible adjustments to `BaseCSVWidget`:

* specify separator
* encode/decode values. 

I'm not yet sure whether the value of these makes them worth bringing into the project.
