### ISSUE TITLE
Internationalization/Language Context for FilterSet

### ISSUE THREAD

**Issue by dwasyl** [carltongibson/django-filter#731]
Hi all,

I might be missing something, but I'm having some trouble getting my `FilterSet` to return content in the correct language. The rest of the application is running fine in the configured languages, but for some reason any custom filters refuse to be translated.

I have a `FilterSet` configured like this:
```
class CustomFilter(django_filters.FilterSet):
    date = django_filters.DateRangeFilter(label=_("Date Range"), widget=LinkWidget())
    categories = django_filters.AllValuesFilter(label=_("Our Categories"), widget=LinkWidget())
```
Now, for some reason, when I call this `FilterSet`:
```
filtered_items = CustomFilter(request.GET, queryset=Item.objects.all())
```
None of the filter field labels are translated in the context returned to my template. If I use the stock `DateRangeFilter` it provides translated values based on the locale files in the `django-filter` package, but if I specify any custom options through a custom `DateRangeFilter` it seems unaware that there is anotehr language activated (unless I manually do so at the top of the class definition).

Through my testing, I figured out that when the `CustomFilter` is run, if doesn't seem to take on the language context of the rest of the application (or even of the stock `FilterSet` class.

I've tried overriding the `__init__` to test for the current set language and it is set properly there, although when I check the language setting in the body of the class it simply reports the default language of the system.

**Comment by rpkilby** [comment]
Hi @dwasyl - tests for translation support only exist for some features, so it's likely that there are some areas that aren't working correctly. The best thing you could do is to provide test cases for expected behavior. 

Translation [tests](https://github.com/carltongibson/django-filter/blob/1.0.4/tests/test_filters.py#L1387-L1413).

**Comment by carltongibson** [comment]
@dwasyl What's your import for `_`?

**Comment by dwasyl** [comment]
@carltongibson I use `from django.utils.translation import ugettext as _`

There are no other problems with translations in my application, so I'm not quite sure what I'm missing here. The inherited `FilterSet` just seems to miss the language context.

@rpkilby I'll take a look through the translation tests, but I'm not entirely sure how to test for these issues.

**Comment by carltongibson** [comment]
@dwasyl That explains it. You need to use `ugettext_lazy` since otherwise the labels are resolved at module import time, which is outside of the `request`'s translation context. 

Review the [Lazy Translation docs](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#lazy-translation). 

Update your import to:

```
from django.utils.translation import ugettext_lazy as _
```

I'm going to assume that solves it. Let me know if not.

**Comment by dwasyl** [comment]
@carltongibson Perfect! That fixed everything (once I'd sorted out some problems with concatenating strings with using ugettext_lazy).

One minor thing I noticed is that in `filters.py` `OrderingFilter`'s `descending_fmt` doesn't have the word `descending` marked for translation.

**Comment by rpkilby** [comment]
@dwasyl - the translations could probably use a little maintenance. eg, the French translations were created four years ago, but the `OrderingFilter` rework was ~8 months ago.

**Comment by carltongibson** [comment]
I'll take PRs for any improvements here.
