### ISSUE TITLE
Is there a way to disable 'exact' lookup?

### ISSUE THREAD

**Issue by berkerpeksag** [carltongibson/django-filter#763]
Here's my `FilterSet`:

```py
from django_filters import rest_framework as filters
from django_filters import STRICTNESS


class ReleaseFileFilter(filters.FilterSet):

    class Meta:
        model = ReleaseFile
        fields = {
            'name': ['exact'],
            'slug': ['exact'],
            'description': ['contains'],
        }
        strict = STRICTNESS.RAISE_VALIDATION_ERROR
```

With `/api/v2/downloads/release_file/?description=Windows`, it returns `ReleaseFile.objects.all()`. I think this is the wrong behavior. I would expect to get a 400 status code with a message saying something like:

```
'exact' is not an allowed filter on the 'description' field.
```

Is there a way to workaround this behavior?

Thank you!

**Comment by rpkilby** [comment]
Hi @berkerpeksag. As you have already determined, the correct query needs to include the lookup.
```
/api/v2/downloads/release_file/?description__contains=Windows
```
What's happening is that the `description` query param is not recognized by the FilterSet, so it's simply ignored when filtering. This request is equivalent to:
```
/api/v2/downloads/release_file/
```

> Is there a way to workaround this behavior?

Unfortunately, the `FilterSet` only recognizes its defined parameters (`name`, `slug`, and `description__contains`). While it can determine which parameters are *not* defined on the `FilterSet`, it's  unable to distinguish between undefined filters (`description`, `description__startswith`), misspellings (`descriptin__cotains`), and completely unrelated query parameters (`page` and `page_size` for pagination). Since the the FilterSet can't generally distinguish these cases, it's not feasible to raise an appropriate error.

For the same reasons above, I wouldn't recommend adding this feature, but it could be done by overriding the `FilterSet.qs` property and checking the `data`'s keys against the defined filters. Something like... 

```python
class CheckedFilterSet(filters.FilterSet):
    @property
    def qs(self):
        errors = [
            ValidationError(f"'{param}' is not a valid filter")
            for param in self.data
            if param not in self.filters
        ]

        if errors:
            raise ValidationError(errors)
                
        return super().qs
```

**Comment by berkerpeksag** [comment]
Thank you for the suggestion, @rpkilby. Unfortunately, I would still need to catch `ValidationError` and raise 400 (and by the way, I'm porting a Tastypie app to DRF so I need to match behavior of the legacy API)

I think ignoring an invalid filter and returning `Model.objects.all()` instead would cause a security problem if `Model` has a lot of records in it (for example, someone can query invalid filters and return the whole table for every request since it makes HTTP caching harder: `/api/v2/downloads/release_file/?foo=bar`, `/api/v2/downloads/release_file/?spam=eggs` etc.)

**Comment by rpkilby** [comment]
> Unfortunately, I would still need to catch ValidationError and raise 400 

Sorry - I should have specified that you'd want to raise DRF's `serializers.ValidationError`, which should be caught by DRF's [exception handling](http://www.django-rest-framework.org/api-guide/exceptions/#exception-handling-in-rest-framework-views) and return an appropriate 400 response. 

> I think ignoring an invalid filter and returning `Model.objects.all()` instead would cause a security problem

I'd argue that the API should only return resources that should already be accessible to the user. In this case, an invalid filter is equivalent to not filtering at all (eg, `/api/v2/downloads/release_file/`). 

That said, you can always extend the above example to ensure that at least one filter is provided.


```python
    @property
    def qs(self):
        # check that at least some filters are present in the query params
        if not set(self.data) & set(self.filters):
            raise serializers.ValidationError('Must provide at least one valid filter')

        # check for invalid filters
        errors = [
            serializers.ValidationError(f"'{param}' is not a valid filter")
            for param in (set(self.data) - set(self.filters))
        ]
        if errors:
            raise ValidationError(errors)
                
        return super().qs
```

Side note - I can't remember if the above is the proper way to raise multiple `ValidationError`s.

**Comment by berkerpeksag** [comment]
Thank you! `serializers.ValidationError` definitely did the trick.
