### ISSUE TITLE
How to translate option values in select field?

### ISSUE THREAD

**Issue by Megido6** [carltongibson/django-filter#767]
i have some select fields in my form.  fields is foreignkeys of other models. 
i got english values from db and want  translate it to other languages in my filter form.

**Comment by rpkilby** [comment]
Hi @Megido6 - it's recommended that usage questions are asked on Stack Overflow since you're more likely to get a timely response. The issue tracker is intended more for bug reports & feature requests. Additionally, it will be helpful to provide an example to more clearly illustrate what you're intending to do.
