### ISSUE TITLE
General Solution for the Lookup Infrastructure

### ISSUE THREAD

**Issue by claytondaley** [carltongibson/django-filter#812]
I have some extra sugar in my case, but it boils down to #675 (and c.f. therein #426 and #538).  In that ticket, you said you were willing to consider a positive, general solution for non-core fields.  I think I have a rough framework for that solution.

===

The Problem:  Like the other tickets, my custom field is based on JSONField so I'm seeing the error:

> AutoFilterSet resolved field 'foo' with 'exact' lookup to an unrecognized field type BarField

As simple queries demonstrate, Django has no trouble with an `exact` lookup for JSONField (or my custom field even though it uses a [custom lookup](https://docs.djangoproject.com/en/1.11/howto/custom-lookups/#a-simple-lookup-example)).  In [filters.filter](https://github.com/carltongibson/django-filter/blob/master/django_filters/filters.py#L174)  `django-filter` appears to delegate the lookup to Django's core behavior:

```
        qs = self.get_method(qs)(**{'%s__%s' % (self.field_name, lookup): value})
```

So far so good.  If a field used *just* this logic by default, it should pickup the right `Lookup` (default or custom) and work fine.

Why doesn't this happen?  [filter_for_lookup](https://github.com/carltongibson/django-filter/blob/9910ee11af8ab54bd788bcf97a20f3e5c02b92b4/django_filters/filterset.py#L353) uses a combination of `FILTER_FOR_DBFIELD_DEFAULTS` and `data.get('filter_class')` to find a filter for a specific field.  If neither of these find a value, it fails.

===

The Solution:  Without fully understanding the architecture, it seems to me that `filter_for_lookup` should return `Filter` as a default.  Thus all fields fall back on the (correct) Django core behavior.

===

The Gotchas:  I tried this locally and ran into the following issues (plus proposed fixes).

1.  ~My `exact` lookup blew up because the type was wrong.  The querystring was still a string when my Django query infrastructure expected JSON (technically, a custom class).  I'm not sure why this isn't a problem for Boolean and Integer.  I think it can be resolved by calling `Field.to_python` on incoming data, but there could be edge cases where this isn't appropriate.~ EDIT:  After some more tracing, this is a side-effect of the next issue.  `to_python` is called, but the **wrong** `to_python` is called because there's no link to the implementation in `form.JSONField`.

2.  (EDIT: simplified)  The base `Filter` doesn't have a `field_class` so the right `to_python` isn't available.  However, I don't think the code needs to declare anything explicitly.   `model.Field.formfield()` returns a `form.Field`.  Filters are initialized using a `model.Field`.  By default, we can create a generic `Filter` and get the right `form.Field` off the `model.Field`.  There may be an argument for keeping the `model.Field` around (my original proposal), but I'm not even sure that's necessary (EDIT2: it is, see below).

EDIT2:  `formfield()` returns an instance while `field_class` expects a class.  Setting `field_class = ModelField().formfield().__class__` would work for most users.  Unfortunately, a LOT of my types are generated dynamically so `MyField().formfield(**kwargs) != MyField.formfield().__class__(**kwargs)` in my code.  To make this a truly general solution, `Filter` need to keep the actual `model.Field` around and call `model.Field.formfield()` (with args/kwargs) [here](https://github.com/carltongibson/django-filter/blob/master/django_filters/filters.py#L159) and [here](https://github.com/carltongibson/django-filter/blob/master/django_filters/filters.py#L161).  

3.  (Optional) This approach may eliminate the need for `FILTER_FOR_DBFIELD_DEFAULTS`.  I'm not 100% sure as relational fields (e.g. [ForeignKey](https://github.com/django/django/blob/master/django/db/models/fields/related.py#L946-L957)) also provide `Field.formfield()` but the return value doesn't exactly match your hardcoded values.  If you need to retain the ability to override fields application-wide, you could switch to a (metaclass-driven) Plugin architecture.  This would make it easier for an application to register their own custom handlers application-wide.

**Comment by claytondaley** [comment]
P.S. I can probably wrap this up in a PR, but wanted to discuss the general approach with you first.  The second bullet is a particularly large shift so it could create unanticipated issues that will be more obvious to you.

**Comment by carltongibson** [comment]
I’m sceptical about this proposal to say the least. My general preference is for less magic rather than more, and this would be a move in the wrong direction for me.

The issue is #675 is about adding a specific JSONFilter that clan handle the various supported lookups on JSONField. i.e. the “general solution” I’m looking for there is a single Filter subclass than handles the wiggles around the supported JSON lookups, not a reworking of the filter definition logic. 

Whilst we haven’t added it yet I’d imagine such a filter to be easy enough. It's also fairly simple to use the method argument to handle this case by case in the meantime. (I imagine most uses come down to the single lookup type.)

**Comment by claytondaley** [comment]
I'm sorry you feel this way.  Django already maintains a relationship between model and form fields using `formfield()`.  There's no magic, just field-by-field defaults.  And so `model.JSONField` already provides a `form.JSONField` with the appropriate linkage.  A custom field will either inherit the behavior of the parent or implement its own (as I did).

If I've gone to the trouble of building a `model.Field` and a related `form.Field` and linking the two using Django's specified behavior, I don't expect to have to tell a Django-based package about it.  Having to repeat myself by informing `django-filter` about that relationship is not DRY -- and the documentation makes it look like I need to inform each and every instance (not just register a default for the type).

Using Django's existing infrastructure is not just DRY, but it expands the package's support to any properly specified field "for free".

**Comment by rpkilby** [comment]
Hi @claytondaley, what you're misunderstanding is that a model's `formfield`s are intended for instance creation and updates. They are not suitable for filtering, thus it doesn't break the DRY principle to not use them in the `FilterSet.form`. Some examples:

- A username field may require a minimum length of 8 characters. When filtering for usernames starting with "joe", it does not make sense to enforce that my query value have a minimum of 8 characters. 
- I may chose to represent unpublished articles as having a null value for it's publish date. While I will want to use a date value for exact or like value matches, an `isnull` lookup instead expects a boolean.
- `AutoField`s don't actually have an associated model `formfield`. No more filtering by ID?
- It does not make sense for a `required` model field to be `required` during filtering.

If django-filter were to be "DRY" in the manner suggested and generate filter fields using the model's `formfield`s, then we'd be fighting issues like the above. #813 works precisely because it's not "DRY" in this fashion and largely ignores these `formfield`s. 

In general, model forms and filter forms are not interchangeable, and it does not make sense to use model form fields as a catchall default. While this may work in your case, it will most likely lead to subtle bugs and frustrating behavior in other cases. I'd rather fail upfront instead.

---- 

To address your issue, you need to create a suitable filter class and can then alter `Meta.filter_overrides` or override the `FilterSet.FILTER_DEFAULTS` dictionary. They have the same format, and per its name, `filter_overrides` overrides the `FILTER_DEFAULTS`. 

- `Meta.filter_overrides` allows you to modify filter generation on a single queryset. 
- `FilterSet.FILTER_DEFAULTS` allows you to override this in your own `FilterSet` base class.

For an example of how you can override the `FILTER_DEFAULTS`, look at `django_filters.rest_framework.filterset.FilterSet`.

**Comment by claytondaley** [comment]
I certainly understand where you're coming from -- as I acknowledged the presence of edge cases in my original proposal.

1. The validation of `exact` (i.e. `=`), is the validation for the existing form field, by definition, so it would generalize to any field.
1. I submit that `isnull` falls into the same bucket.  Your argument is true regardless of the field's type so a `BaseFilterSet` should return a `BooleanField` filter for any `isnull` filter.  It's easy enough to confirm that the model field supports `isnull` before doing so (and error otherwise).
1. The next layer are cases (e.g. `gt`, `lt`, and `contains`) where the `to_python` method is expected to be valid, but the validation is too stringent.  A reasonable default is to disable all validation (including `required=`).  If someone wants additional validation, they can always override the default behavior. (In quick testing, input failures were indistinguishable when validation was disabled.)
1. While I speculated that the `FILTER_DEFAULTS` might be removed, `AutoField` is obviously a case where it cannot.

I think there's a solid argument for sane defaults in the vast majority of cases.  It's notable (if unsurprising) that our discussion has focused on different lookup types.  To minimize bugs produced by edge cases, it seems reasonable to restrict default behaviors to specific lookup types using a whitelist.

**Comment by rpkilby** [comment]
Hi @claytondaley. I've put a little thought into this, and I don't really see a viable solution. In short, options either seem to increase complexity or break expectations about the form validation process. Regardless, if you think you have a solution, it would be better discuss the details in a PR.

> I certainly understand where you're coming from -- as I acknowledged the presence of edge cases in my original proposal.

The majority of model fields have the ~18 standard lookups. Two of these lookups (`exact` and `iexact`) work with the field produced by `field.formfield()`. This compatibility is the edge case - the majority of lookups would require altering the field. 

> A reasonable default is to disable all validation

At it's core, the `FilterSet` and `Filter` are an abstraction of the `Form` and form `Field`. The former know how to construct the latter, and then how to filter a queryset with the resulting cleaned data. That is to say, 50% of the `FilterSet`'s utility is to construct a standard django form suitable for *validating user input*. To complicate or disable validation is counter to the `FilterSet`'s purpose.

**Comment by claytondaley** [comment]
The `exact` lookup is a trivial case of DRY.  If you're not even sold on that case, I can't imagine that you'd accept a PR... so I'm not going to waste company time.

And if it ends up being worth my company's time to do locally, it's going to have to be on the 1.x branch since you've decided to exclude the universe of PY2 contributors from further participation in the project.

**Comment by rpkilby** [comment]
> The `exact` lookup is a trivial case of DRY. 

My point is that it looks like it's the *only* DRY case where `field.formfield()` is suitable in it's default state. Beyond that, you either have to alter the form field, or override the form's field cleaning process. For argument, consider a CharField with min/max length validation. I can think of two plausible options:

- Build the appropriate set of `kwargs` that are passed to `field.formfield()`.
  ```python
  # NOTE: We cannot inspect the form field class ahead of time, as .formfield() creates an 
  # instance. However, we need to know these kwargs before calling .formfield()... To work
  # around this, we either have to create two fields - a dummy for getting the type, then 
  # the actual - or we have to use the model field.
  DB_FORMFIELD_DEFAULTS = {
      models.CharField: {'min_length': None, 'max_length': None, 'required': False},
      ...
  }

  class Filter(...):
      @property
      def field(self):
          # defaults for disabling validation
          kwargs = DB_FORMFIELD_DEFAULTS.get(type(self.model_field), {})

          # user-provided field kwargs during Filter initialization
          kwargs.update(self.field_kwargs)

          # do initialization logic currently found in the .field() property 
          ...

          return self.model_field.formfield(**defaults)
  ```
- Modify the form's cleaning process to call `field.to_python()` instead of `field.clean()`, since the `clean` method performs all of the provided validation checks.
  ```python
  class CleanFieldsOverride(self._meta.form):
      def _clean_fields(self):
          for field in self.fields.values():
              field.clean = field.to_python
          return super()._clean_fields()
  ```

Here are the problems as I see it:
- Building these `kwargs` has the exact same issue as `FILTER_FOR_DBFIELD_DEFAULTS` - it's just been punted from filter class defaults to form field `kwargs` defaults. Additionally, this map of field defaults for disabling validation is much more cumbersome to maintain than just needing to know the underlying form `field_class`. eg, if a new validation parameter is added, these defaults have to be updated. In comparison, the current implementation does not need to care.
- While terse, swapping the field's `.clean()` method with `.to_python()` is a nonstarter on two fronts:
    - This breaks fundamental user expectations on form validation. If users create a custom form field that defines its own `.clean()` method, then they expect this to be called. 
    - It is not always sufficient to just call `.to_python()` instead of `.clean()`. eg, `TypedChoiceField` performs its type coercion in `.clean()`. We would need to provide special handling in `._clean_fields()`, or `TypedChoiceField` would just be broken.

----

> If you're not even sold on that case, I can't imagine that you'd accept a PR... so I'm not going to waste company time.

I don't mean to be overly discouraging, but in trying to imagine a possible implementation I don't see one that's viable. I don't want you to unnecessarily waste your time if we can determine viability upfront. That said, you might have a completely different implementation in mind. If that's the case, great - let's discuss the more concrete details in a PR. I honestly don't see the harm in doing so:

- If your proposal is successful, great. You'll still need to backport it to your company's fork, but come 2020, you'll need to migrate to python 3 anyway and can move back to the official django-filter package. 
- If your proposal isn't merged, it at least allows others provide feedback. For major feature proposals, I usually go through several iterations. Feedback+critique is incredibly valuable.

> since you've decided to exclude the universe of PY2 contributors from further participation in the project

Django 1.11 is ending mainstream support next month, which marks the end of all major development in the Django+python 2 sphere. The future lies with python 3, and it makes sense for django-filter's upcoming 2.x release to follow suit.

**Comment by carltongibson** [comment]
> ... worth my company's time...

Your company's time is best spent upgrading to Python 3. It seriously is the biggest win you could make here.

**Comment by claytondaley** [comment]
> For argument, consider a CharField with min/max length validation. I can think of two plausible options

What is the current code doing?  I may be missing something but it looks to me like it's implicitly dropping all validation.

**Comment by claytondaley** [comment]
> I don't mean to be overly discouraging, but in trying to imagine a possible implementation I don't see one that's viable. I don't want you to unnecessarily waste your time if we can determine viability upfront. 

That's why I asked the question before investing the time.  I'd rather be discouraged now.  I contribute back to projects (in no small part) because it's usually DRY to fix problems once and for everyone.  That often requires big changes... which can run afoul of architectural constraints or maintainer design decisions.

**Comment by carltongibson** [comment]
It **is** also a maintainer decision. 😃

> My general preference is for less magic rather than more, and this would be a move in the wrong direction for me.

A lot, if not most, of what we do (not just here) is seeking clear _declarative_ implementations. These are ultimately the easiest things to understand, to work with, and to maintain. My experience is that every time (not just here) we add a little bit of magic in order to be DRY™ we end up creating a source of problems and misunderstandings. 

Much like defining serialisers or filters or forms or models or admins, a little bit of repetition is actually a virtue. (Despite the DRY mantra.)
