### ISSUE TITLE
Add a demo page?

### ISSUE THREAD

**Issue by d33tah** [carltongibson/django-filter#838]
Hi! I'm curious how this project works and would love to see a demo page or some screenshots in the README/docs. Could you add that?

**Comment by rpkilby** [comment]
Hi @d33tah. Overhauling the docs is one of the objectives for the 2.0 release.

**Comment by yatahaze** [comment]
I agree totally. I'm trying to use this for the first time and struggling. 

I've got the filters showing and working, however I'm not sure if I can make the filters use the resulting queryset (rather than just anything possible). 

I get dropdowns with all sorts of options it lets me choose together and end up with 0 results. Would like to have more examples.

**Comment by carltongibson** [comment]
This may happen at some point. More likely, you could write up a blog post or contribution to the docs.
