### ISSUE TITLE
Using the ordering filter with a non-deterministic ordering and pagination might lead to items being shown twice on different pages and other items not being shown at all

### ISSUE THREAD

**Issue by fuzzylogic2000** [carltongibson/django-filter#862]
When we used the OrderingFilter in a FlterSet used in a ListView with pagination, it worked fine for deterministic orderings like date of creation, but would show some items twice when the ordering was non-deterministic like the number of comments for a blog post. This happened when the last items on one page and some items on the next page had the same value for the field they were ordered by.

An inspection of the actual SQL-query showed that the querysets were only ordered by the ordering choice, but not by the meta ordering-value of Model or FilterSet as well. So depending on the state of the DB, in the query for the next page, some items were added to the qs again while others were never added. We fixed that locally by over-writing the [filter method]([https://github.com/carltongibson/django-filter/blob/master/django_filters/filters.py#L619]) and adding a deterministic ordering to the ordering-list.

That seems to be reproducible only in postgress, not SQLite.

**Comment by carltongibson** [comment]
OK. That sounds interesting. 

Any chance you can narrow it done to a test case?

**Comment by rpkilby** [comment]
My understanding is that the `ordering` option simply provides a default call to `order_by`. Subsequent `order_by` calls clear the previous call, so if you want to order by two factors (the model's meta ordering and the selected choice), you should subclass `OrderingFilter` and  override the `.filter()` method. eg,

```python
class MyOrderingFilter(filters.OrderingFilter):
    def filter(self, qs, value):
        # CSV-based filters always receive a list or None
        value = ['default_ordering'] + value if value else ['default_ordering']
        return super().filter(qs, value)
```

**Comment by kleingeist** [comment]
> Any chance you can narrow it down to a test case?

it is difficult to write a python test case, as this depends on the database. the sql standard does not define any order of the rows apart from the one given by an explicit `ORDER BY` statement. thus if the rows are ordered by the comments, there is no guarantee of the order of the rows within the same number of comments.
to demonstrate the problem i created a small sqlfiddle with example data where i could reproduce the problem: http://sqlfiddle.com/#!9/fe1deb/5
note, that the row with pk=2 never occurs in any of the paginated result sets if the data is only orderd by the comment count.

explicitly ordering by the pk as the second argument fixes the problem. we fixed our specific problem by appending the pk to the `order_by` clause by overwriting the `filter` function (see https://github.com/liqd/a4-advocate-europe/commit/0767b3e65fb9e836e5874f8c268e0b4a160c5865 ).
but we still think this is a problem as rows may get lost from the user viewpoint if filters and pagination are used together. the problem is neither documented, nor is there an easy way to  to add define a second field for ordering
for example it would be nice if we could just use something like:
```
ordering = OrderingFilter(
        fields=(
            ('-created', 'newest'),
            (('-comment_count', 'pk), 'comments'),
            ('idea_title', 'title'),
        ),
        choices=ORDERING_CHOICES,
        empty_label=None,
        widget=OrderingFilterWidget
    )
```

**Comment by fuzzylogic2000** [comment]
@kleingeist Thanks for that perfect example!
@carltongibson @rpkilby And thanks for answering that quickly!

> so if you want to order by two factors (the model's meta ordering and the selected choice), 
The problem is not that we want to order by two factors, we don't care about the second factor, we just don't want any items to be lost inbetween DB queries.

> you should subclass OrderingFilter and override the .filter() method
Thanks, that is exactly what we did and it solved the problem for us. But as a paginated list and ordering by a value that produces non-deterministic orderings (number of legs of animals, number of ice cream flavors sold, ...) is a common pattern, it would be good to either make sure it can't happen or state somewhere that this might be a problem.
