### ISSUE TITLE
Add Documentation / API for MultiValueCharField

### ISSUE THREAD

**Issue by kunalgrover05** [carltongibson/django-filter#890]
I had a use case where I wanted to allow filtering with multiple values on one field. I think it would be a fairly common use-case where multiple matches are needed.

I think the same might hold place in documentation or the API itself.
Here's the implementation snippet:
```
class MultiValueCharFilter(filters.Filter):
    def __init__(self, *args, **kwargs):
        self.method_multivalue = kwargs.pop('method_multivalue')
        super(MultiValueCharFilter, self).__init__(*args, **kwargs)

    def filter(self, qs, value):
        q = Q()
        for v in value.split('|'):
            q = q | Q(**{self.method_multivalue: v})
        return qs.filter(q)

names = MultiValueFilter(method_multivalue='name')
```

Usage: ?names=a|b|c

**Comment by Antwan86** [comment]
It'd rather be more consistent to use `?names=a&names=b&names=c` as a querystring

**Comment by kunalgrover05** [comment]
I don't think I would agree, we are looking for an OR syntax while adding multi value keys. The best way would be to use a different syntax.

**Comment by Antwan86** [comment]
`?names=a&names=b&names=c` is already the expected behaviour for `MultipleChoiceField` (which boolean logic being `OR` as default), because it is the standard way to build arrays from querystrings using Django [`QueryDict`](https://github.com/django/django/blob/2.0.5/django/http/request.py#L351).

    from django.http.request import QueryDict
    QueryDict('name=a&name=b&other=c')
    
    <QueryDict: {u'other': [u'c'], u'name': [u'a', u'b']}>

Other implementations are much less djangonic and easy to use/discover.
