### ISSUE TITLE
Clarification of default lookup option for generated fields

### ISSUE THREAD

**Issue by thclark** [carltongibson/django-filter#931]
Using the `rest_framework` filters.

In the [docs on declaring filterable fields](https://django-filter.readthedocs.io/en/master/ref/filterset.html#declaring-filterable-fields), there are two methods for declaring the fields:

- a list of field names
- a dictionary of field names mapped to a list of lookups

I'd made an assumption that the list of field names syntax...
```
filter_fields = ('created', )
```
is equivalent to...
```
filter_fields = {
    'created': ['exact', 'contains', 'gt', 'lt', 'gte', <and all the others>],
}
```

Using a DRF Viewset with the `filter_fields = ('created', )`, my code to filter `.../my/endpoint/?created__gt=2018-06-29T08:50:14.109Z` does not work - simply returning all results instead. Replacing the property with the dictionary syntax, it works fine.

### Question 1 - Is this expected behaviour?
I assume it is, because expecting django_filter to automagically determine which `LOOKUP_TYPES` are relevant for each field might be a bit much. But I wanted to check.

### Question 2 - Can we clarify this in the docs?

Please could we clarify this in the docs ([here](https://github.com/carltongibson/django-filter/blob/b1f1c6592ef64a2172ec39040607a9c0b0714140/docs/ref/filterset.txt#L44))? I'd suggest:

> The ``fields`` option is combined with ``model`` to automatically generate
filters **with the ``'exact'`` lookup option enabled**. Note that generated filters...

I'm happy to make a PR for this if it helps.

**Comment by rpkilby** [comment]
Hi @thclark. Quoting the docs:

> The list syntax will create an `exact` lookup filter for each field included in `fields`. 

So, `filter_fields = ('created', )` would just be equivalent to:

```python
filter_fields = {
    'created': ['exact'],
}
```

As you found, you need to explicitly provide the larger list of lookups. 

----

> expecting django_filter to automagically determine which `LOOKUP_TYPES` are relevant for each field might be a bit much. But I wanted to check.

Generating all lookups for a field is possible (this behavior does exist in `django-rest-framework-filters`, although I recommend *not* using it. This is because there are between 20 - 30 lookups per field (depending on the number of transforms. e.g., datetime fields). With a handful of fields, you'd quickly end up with hundreds of filters. While django-filters is pretty fast, creating hundreds of unused filters will end up increasing your response time.

**Comment by carltongibson** [comment]
The docs already say this, just below the examples: 

> The list syntax will create an ``exact`` lookup filter for each field included
in ``fields``.
