### ISSUE TITLE
Travis build failing due to incompatibility between tox and detox

### ISSUE THREAD

**Issue by therefromhere** [carltongibson/django-filter#990]
eg: https://travis-ci.org/carltongibson/django-filter/jobs/446129405

`Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/py/_path/local.py", line 152, in __init__
    path = fspath(path)
TypeError: expected str, bytes or os.PathLike object, not tuple`

see https://github.com/tox-dev/detox/issues/33

**Comment by obestwalter** [comment]
Hi @therefromhere, I would be interested to know why detox is used for parallelization rather than Travis.

**Comment by therefromhere** [comment]
Hi @obestwalter , I've no idea :)  I was just fixing the build

**Comment by therefromhere** [comment]
@obestwalter by the way see #996 for pr to remove detox

**Comment by carltongibson** [comment]
We used to duplicate the tox config in the travis config. 

I basically got fed up with this so we had travis run tox. 

This meant that all the runs appear in a single build on travis. 

That’s OK but detox (when it works) splits the builds out so they’re slightly more accessible in the travis UI. 

Given the issues with detox we can live without that. 

(Also we’re going to give Azure Pipelines a run)

**Comment by rpkilby** [comment]
Hi @obestwalter. The problem is that Travis's parallelization is limited by its cap of 5 concurrent jobs. Given that django-filter has ~16 test envs and that it takes about a minute to initialize the container, running each of these individually in its own Travis job does pad out the total run time. We use tox-travis to group by the Python version factor, reducing the number of Travis jobs to 6 or so, shaving off a couple of minutes.

Using detox was just another factor that could potentially speed up the build. The test suite itself is fairly quick to run at less than two seconds, but installing the dependencies is ~10-30 seconds per test env. Since detox installs and runs in parallel, this had the potential for shaving off another minute or so. In practice, it doesn't matter that much. Sometimes it's faster, sometimes it's not.

For comparison, here are three different Travis configurations:

| Configuration | Commit | Travis Build | Wall time | CPU time |
| -------------- | ------- | ------------ | --------- | --------- |
| Travis+tox | 82fbea2484f5df1bafae082b720a291d0e0fca2d | [Travis Build](https://travis-ci.org/carltongibson/django-filter/builds/450130003) | 5 min 8 sec | 21 min 7 sec |
| Travis+tox+tox-travis | 7528fc551d3dee62a978585a92398233f94da68b | [Travis Build](https://travis-ci.org/carltongibson/django-filter/builds/450132666) | 2 min 54 sec | 11 min 15 sec |
| Travis+detox+tox-travis | 4041bfe007ee71334aa8810cdf0c193f64289e5c | [Travis Build](https://travis-ci.org/carltongibson/django-filter/builds/450130923) | 2 min 44 sec | 9 min 19 sec |
